%% ** Script for timeseries analysis **

% Declare globally shared variables
global SCRSZ WHFIG WHTRCFIG POSITIONFIG POSITIONTRCFIG POSITIONROISELECT FONTSIZE...
    TRCYLABEL TRCYLABELDFOF TRCXLABEL TRCPLOTCOL1 TRCPLOTCOL2 TRCALPHA THRESHLW...
    THRESHALPHA EVPLOTCOL PLOTPEAKS THRESHOLDTYPE THRESHOLD PEAKTHRESHOLD SMTHWIN...
    ROICNTID FIGCOUNTER CURRFILE SAVEPARENT FTIME ISBGSUB WHREVFIG evINFO BASEPOINTS PREPOINTS...
    POSTPOINTS LW1 LW2 XTYPE FFORMAT XLINEALPHA SAVEPATH FTIMEVEC

addpath('C:\Program Files\MATLAB\libraries\gramm-master\');

% Initiate variables
FIGCOUNTER = 0;
ROICNTID = 1;
CURRFILE = 1;
SCRSZ = get(0, 'Screensize'); SCRSZ = SCRSZ(3:4);
WHFIG = [800 600];
WHTRCFIG = [1000 600];
WHREVFIG = [400 600];
POSITIONFIG = [100 SCRSZ(2)-WHFIG(2)-100 WHFIG];
POSITIONTRCFIG = [100 SCRSZ(2)-WHFIG(2)-100 WHTRCFIG];
POSITIONROISELECT = [0.05 0.1 0.9 0.85];
FONTSIZE = 8;
LW1 = 1;
LW2 = 1.5;
TRCYLABEL = 'Av. Int.';
TRCYLABELDFOF = 'DeltaF/F';
TRCXLABEL = 'time [s]';
TRCPLOTCOL1 = [0.6510 0.0667 0.2784];
TRCPLOTCOL2 = [0.0471 0.3137 0.4588];
TRCALPHA = 0.25;
THRESHLW = 1;
THRESHALPHA = 0.7;
EVPLOTCOL = [0 0.1882 0.1059];
PLOTPEAKS = false; % otherwise plot THRESHOLD crossings
THRESHOLDTYPE = 'dF';
THRESHOLD = 6;
PEAKTHRESHOLD = 0;
SMTHWIN = 0; % smoothing for peak detection [s]
SAVEPARENT = [];
FTIME = 0.1; % in [s]
% FTIMEVEC = [];
ISBGSUB = false;
evINFO = struct();
BASEPOINTS = 10;
PREPOINTS = 20;
POSTPOINTS = 50;
XTYPE = 's';
FFORMAT = '.xlsx';
XLINEALPHA = 0.1;
SAVEPATH = '';

close all;
ini_ctrl_box_timescan();
